package com.github.a2g.core.primitive;

public interface LogNames {
	String MOVE_PERFORMER = "MOVE";
	String LOADING = "Loading";
	String LOADING_ANIM = "LOADING_ANIM";
	String RUNNER = "RUNNER";
	String RUNNER_REFCOUNT = "RUNNER_REFCOUNT";
	String COMMANDS_VIA_GUI = "COMMAND_MANUAL";
	String COMMANDS_AUTOPLAY = "COMMAND_AUTOPLAY";
	String HTML5CANVAS = "HTML5CANVAS";
	String ADDING_ANIM_TO_SOC_MAP = "ADDING_ANIM_TO_SOC_MAP";
	String IMAGE_DUMP = "IMAGE_DUMP";
	String ACTIONS_AS_THEY_ARE_EXECUTED = "ACTIONS_EXECUTED";
	String KEY_ENTRY = "KEY_ENTRY";
	String ACTIONS_FLATTENED_B4_EXECUTION = "ACTIONS_FLATTENED_B4_EXECUTION";
	String WALK_MULTI_PERFORMER = "WALK_MULTI_PERFORMER";
	String MULTIWALKER = "A";
	String B = "B";
	String C = "C";
	String D = "D";
	String ANIMATIONS_AS_THEY_ARE_GOT = "ANIMATIONS_AS_THEY_ARE_INDEXED";
	String LOADNEXT = "LOADNEXT";
}
