package com.github.a2g.core.interfaces;

public interface IScenePresenterFromActions extends
IScenePresenterFromAlignAction, IScenePresenterFromHideAllAction,
IScenePresenterFromMoveAction, IScenePresenterFromPlayAction,
IScenePresenterFromTalkAction, IScenePresenterFromScrollAction,
IScenePresenterFromSetActiveFrameAction,
IScenePresenterFromSetBaseMiddleXAction,
IScenePresenterFromSetBaseMiddleYAction,
IScenePresenterFromSetCurrentAnimationAction,
IScenePresenterFromSetDisplayNameAction,
IScenePresenterFromSetInitialAction,
IScenePresenterFromSetToInitialPosAction,
IScenePresenterFromSetValueAction, IScenePresenterFromSetVisibleAction,
IScenePresenterFromShareAction, IScenePresenterFromSwapAction,
IScenePresenterFromSwitchAction, IScenePresenterFromWaitAction,
IScenePresenterFromWalkAction, IScenePresenterFromWalkScrollAction {
}
